### ISSUE TITLE
Relay starts guide

### ISSUE THREAD

**Issue by lightningorb** [monty888/nostrpy#1]
Started your relay using python3 run_relay.py, not too sure where to go from here. PS i have a lot of kivy and python experience, so can contribute once i'm up & running.

**Comment by lightningorb** [comment]
Ah, NVM i found the mirror relay script

**Comment by monty888** [comment]
Hi, I've started splitting/refactoring this and so the base code/some examples is now monstr repository, and some terminal stuff in monstr_terminal. Hopefully some web stuff to. I want to make sure the Client/ClientPool classes work correcty, Think I might not be using the websockets-client totally correctly..
